drop table if exists model_usage;
drop table if exists scheduled_tasks;
drop table if exists notifications;
drop function if exists append_audit_log(text, text, uuid, jsonb, jsonb, text, bigint, bigint, bigint, bigint, bigint, bigint, uuid, bigint);
drop trigger if exists audit_logs_append_only on audit_logs;
drop function if exists reject_audit_log_mutation();
drop table if exists audit_logs;
drop table if exists secrets_metadata;
drop table if exists memories;
drop table if exists artifacts;
drop table if exists files;
drop table if exists tool_executions;
drop table if exists agent_runs;
drop table if exists approvals;
drop table if exists mission_events;
drop table if exists mission_steps;
drop table if exists missions;
drop table if exists tools;
drop table if exists agents;
drop table if exists project_rules;
drop table if exists project_members;
drop table if exists projects;
drop table if exists machine_capabilities;
drop table if exists machines;
drop table if exists telegram_accounts;
drop table if exists users;
drop table if exists schema_migrations;
drop extension if exists pgcrypto;
